export const queryKeys = {
  authUser: ['auth', 'user'] as const,
  patients: ['patients'] as const,
  patientDetail: (patientId: string) => ['patients', patientId] as const,
  consultations: ['consultations'] as const,
  consultationById: (consultationId: string) => ['consultations', consultationId] as const,
  consultationTemplates: ['consultation-templates'] as const,
  appointments: ['appointments'] as const,
  appointmentsByDate: (date: string) => ['appointments', date] as const,
  bioimpedancePreview: ['bioimpedance', 'preview'] as const,
  bioimpedanceEvolution: (patientId?: string) => ['bioimpedance', 'evolution', patientId ?? 'all'] as const,
  templateBuilderElements: ['template-builder', 'elements'] as const,
  templateBuilderVariables: ['template-builder', 'variables'] as const,
  clinics: ['clinics'] as const,
  scores: ['scores'] as const,
  scoresHistory: (patientId: string, scoreName?: string) =>
    ['scores', 'history', patientId, scoreName ?? 'all'] as const,
  scoresLatest: (patientId: string, scoreName?: string) => ['scores', 'latest', patientId, scoreName ?? 'all'] as const,
  protocols: ['protocols'] as const,
  glucose: (patientId: string) => ['glucose', patientId] as const,
  labResults: (patientId: string) => ['lab-results', patientId] as const,
  prescriptionsByPatient: (patientId: string) => ['prescriptions', 'patient', patientId] as const,
  activePrescriptions: (patientId: string) => ['prescriptions', 'active', patientId] as const,
  prescriptionsByConsultation: (consultationId: string) =>
    ['prescriptions', 'consultation', consultationId] as const,
  drugTemplates: ['prescriptions', 'drug-templates'] as const,
  analysis: (patientId: string) => ['analysis', patientId] as const,
  glucoseHistory: (patientId: string) => ['glucose', patientId, 'history'] as const,
  glucoseAnalysis: (patientId: string) => ['glucose', patientId, 'analysis'] as const,
  labResultsHistory: (patientId: string, examName?: string) =>
    ['lab-results', patientId, examName ?? 'all'] as const,
};
