-- Initial migration for Supabase/PostgreSQL 16
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

DO $$ BEGIN
  CREATE TYPE user_role AS ENUM ('DOCTOR','RECEPTIONIST','ADMIN','PATIENT');
  CREATE TYPE biological_sex AS ENUM ('MALE','FEMALE','INTERSEX','NOT_INFORMED');
  CREATE TYPE record_status AS ENUM ('ACTIVE','INACTIVE','ARCHIVED');
  CREATE TYPE consent_status AS ENUM ('GIVEN','REVOKED','EXPIRED');
  CREATE TYPE consultation_status AS ENUM ('DRAFT','IN_PROGRESS','COMPLETED','SIGNED','CANCELED');
  CREATE TYPE appointment_status AS ENUM ('SCHEDULED','CONFIRMED','WAITING','IN_PROGRESS','COMPLETED','CANCELED','NO_SHOW');
  CREATE TYPE document_type AS ENUM ('PRESCRIPTION','CERTIFICATE','REPORT','AI_REPORT','LAB_ORDER','CONSENT','BIOIMPEDANCE','OTHER');
  CREATE TYPE signature_status AS ENUM ('PENDING','SIGNED','REJECTED');
  CREATE TYPE reminder_channel AS ENUM ('PUSH','SMS','WHATSAPP','EMAIL');
  CREATE TYPE service_contract_type AS ENUM ('PRIVATE','INSURANCE','SOCIAL');
  CREATE TYPE service_type AS ENUM ('FIRST_CONSULTATION','FOLLOW_UP','PROCEDURE','EXAM','OTHER');
  CREATE TYPE audit_action AS ENUM ('INSERT','UPDATE','DELETE','ACCESS','EXPORT');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Core
CREATE TABLE IF NOT EXISTS "User" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,email text UNIQUE NOT NULL,"passwordHash" text NOT NULL,role user_role NOT NULL,"isActive" boolean NOT NULL DEFAULT true,"lastLoginAt" timestamptz,"createdAt" timestamptz NOT NULL DEFAULT now(),"updatedAt" timestamptz NOT NULL DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "UserProfile" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"userId" uuid UNIQUE NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,"fullName" text NOT NULL,specialty text,crm text,cpf text,phone text,metadata jsonb,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "Clinic" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,name text NOT NULL,cnpj text,phone text,color text,"logoUrl" text,address jsonb,settings jsonb,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "ClinicUser" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"clinicId" uuid NOT NULL REFERENCES "Clinic"(id) ON DELETE CASCADE,"userId" uuid NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,"roleAtClinic" user_role NOT NULL,permissions jsonb,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid,UNIQUE("clinicId","userId"));

-- Patient domain
CREATE TABLE IF NOT EXISTS "Patient" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"clinicId" uuid REFERENCES "Clinic"(id),"fullName" text NOT NULL,"preferredName" text,"birthDate" timestamptz NOT NULL,"biologicalSex" biological_sex NOT NULL,"genderIdentity" text,cpf text UNIQUE NOT NULL,rg text,whatsapp text NOT NULL,email text,"maritalStatus" text,occupation text,"educationLevel" text,nationality text,naturalness text,"fatherName" text,"motherName" text,"emergencyName" text,"emergencyRelation" text,"emergencyPhone" text,"healthPlanProvider" text,"healthPlanName" text,"healthPlanNumber" text,"clinicalNotes" text,tags jsonb,status record_status DEFAULT 'ACTIVE',"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "PatientAddress" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"patientId" uuid NOT NULL REFERENCES "Patient"(id) ON DELETE CASCADE,"zipCode" text NOT NULL,street text NOT NULL,number text NOT NULL,complement text,neighborhood text NOT NULL,city text NOT NULL,state text NOT NULL,"isPrimary" boolean DEFAULT true,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "PatientConsent" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"patientId" uuid NOT NULL REFERENCES "Patient"(id) ON DELETE CASCADE,"consentType" text NOT NULL,status consent_status NOT NULL,"acceptedAt" timestamptz,"revokedAt" timestamptz,"ipAddress" text,"userAgent" text,"termsVersion" text NOT NULL,metadata jsonb,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "PatientPortalAccount" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"patientId" uuid UNIQUE NOT NULL REFERENCES "Patient"(id) ON DELETE CASCADE,email text UNIQUE NOT NULL,"passwordHash" text NOT NULL,"isActive" boolean DEFAULT true,"verifiedAt" timestamptz,"lastLoginAt" timestamptz,"resetToken" text,"resetTokenExpiresAt" timestamptz,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);

-- Clinical and supporting entities (full parity with Prisma model names)
-- For brevity in this initial SQL, each table contains UUID PK, tenantId, domain columns, audit columns.
CREATE TABLE IF NOT EXISTS "Consultation" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"patientId" uuid NOT NULL REFERENCES "Patient"(id) ON DELETE CASCADE,"doctorId" uuid NOT NULL,"appointmentId" uuid,"versionGroupId" uuid NOT NULL,"versionNumber" int NOT NULL DEFAULT 1,"previousVersionId" uuid,status consultation_status NOT NULL DEFAULT 'DRAFT',"consultationDate" timestamptz NOT NULL,reason text,"contentJson" jsonb,"aiSummary" text,"signedAt" timestamptz,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid,UNIQUE("versionGroupId","versionNumber"));
CREATE TABLE IF NOT EXISTS "SOAPRecord" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"consultationId" uuid UNIQUE NOT NULL REFERENCES "Consultation"(id) ON DELETE CASCADE,subjective text,objective text,assessment text,"plan" text,"rawData" jsonb,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "AnamnesisRecord" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"consultationId" uuid UNIQUE NOT NULL REFERENCES "Consultation"(id) ON DELETE CASCADE,"chiefComplaint" text,"historyPresentIllness" text,"pastIllnesses" text,surgeries text,allergies text,"currentMeds" text,"familyHistory" text,"socialHistory" text,"lifestyleData" jsonb,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "PhysicalExam" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"consultationId" uuid UNIQUE NOT NULL REFERENCES "Consultation"(id) ON DELETE CASCADE,"bloodPressure" text,"heartRate" text,"respiratoryRate" text,temperature text,"oxygenSaturation" text,"weightKg" numeric(5,2),"heightCm" numeric(5,2),bmi numeric(5,2),"narrativeText" text,"systemsJson" jsonb,"structuredJson" jsonb,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "Diagnosis" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"consultationId" uuid NOT NULL REFERENCES "Consultation"(id) ON DELETE CASCADE,"cid10Code" text,"diagnosisText" text NOT NULL,"riskLevel" text,"isPrimary" boolean DEFAULT false,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);

-- Remaining tables
CREATE TABLE IF NOT EXISTS "BioimpedanceExam" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"patientId" uuid NOT NULL REFERENCES "Patient"(id) ON DELETE CASCADE,"examDate" timestamptz NOT NULL,"deviceName" text,"weightKg" numeric(5,2),"bodyFatPct" numeric(5,2),"muscleMassKg" numeric(5,2),"visceralFatLevel" numeric(5,2),"segmentData" jsonb NOT NULL,notes text,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "BodyCircumference" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"bioimpedanceExamId" uuid NOT NULL REFERENCES "BioimpedanceExam"(id) ON DELETE CASCADE,region text NOT NULL,"valueCm" numeric(5,2) NOT NULL,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "GlucoseLog" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"patientId" uuid NOT NULL REFERENCES "Patient"(id) ON DELETE CASCADE,"measuredAt" timestamptz NOT NULL,"glucoseMgDl" int NOT NULL,context text,notes text,source text,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "GlucoseTarget" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"patientId" uuid NOT NULL REFERENCES "Patient"(id) ON DELETE CASCADE,period text NOT NULL,"minMgDl" int NOT NULL,"maxMgDl" int NOT NULL,active boolean DEFAULT true,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "GlucoseReminder" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"patientId" uuid NOT NULL REFERENCES "Patient"(id) ON DELETE CASCADE,title text NOT NULL,"scheduleCron" text,"hourOfDay" text,timezone text,channel reminder_channel NOT NULL,active boolean DEFAULT true,payload jsonb,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);

CREATE TABLE IF NOT EXISTS "LabResult" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"patientId" uuid NOT NULL REFERENCES "Patient"(id) ON DELETE CASCADE,"examDate" timestamptz NOT NULL,source text,"fileUrl" text,summary text,"rawJson" jsonb,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "LabResultItem" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"labResultId" uuid NOT NULL REFERENCES "LabResult"(id) ON DELETE CASCADE,name text NOT NULL,value numeric(10,2),"textValue" text,unit text,"referenceRange" text,status text,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "ExamRequest" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"patientId" uuid NOT NULL REFERENCES "Patient"(id) ON DELETE CASCADE,"consultationId" uuid,"requestedAt" timestamptz DEFAULT now(),notes text,status text NOT NULL,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "ExamRequestItem" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"examRequestId" uuid NOT NULL REFERENCES "ExamRequest"(id) ON DELETE CASCADE,"examName" text NOT NULL,"loincCode" text,urgency text,instructions text,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);

CREATE TABLE IF NOT EXISTS "MedicalDocument" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"patientId" uuid NOT NULL REFERENCES "Patient"(id) ON DELETE CASCADE,"consultationId" uuid,"templateId" uuid,"documentType" document_type NOT NULL,title text NOT NULL,"contentJson" jsonb NOT NULL,"renderedPdfUrl" text,status text NOT NULL,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "DocumentTemplateV2" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,name text NOT NULL,description text,"documentType" document_type NOT NULL,"schemaVersion" int DEFAULT 2,"contentJson" jsonb NOT NULL,"isActive" boolean DEFAULT true,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "DocumentSignature" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"documentId" uuid NOT NULL REFERENCES "MedicalDocument"(id) ON DELETE CASCADE,"signerUserId" uuid,"signerPatientId" uuid,"signedAt" timestamptz,status signature_status NOT NULL,"certificateData" jsonb,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);

CREATE TABLE IF NOT EXISTS "Prescription" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"patientId" uuid NOT NULL REFERENCES "Patient"(id) ON DELETE CASCADE,"consultationId" uuid,"prescribedAt" timestamptz DEFAULT now(),notes text,status text NOT NULL,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "PrescriptionItem" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"prescriptionId" uuid NOT NULL REFERENCES "Prescription"(id) ON DELETE CASCADE,"medicationName" text NOT NULL,dosage text NOT NULL,route text,frequency text NOT NULL,"durationDays" int,instructions text,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);

CREATE TABLE IF NOT EXISTS "Disease" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,code text NOT NULL,name text NOT NULL,synonyms jsonb,metadata jsonb,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "Medication" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,name text NOT NULL,"activeIngredient" text,"atcCode" text,metadata jsonb,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "ClinicalProtocol" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"parentProtocolId" uuid,name text NOT NULL,"diseaseId" uuid,"protocolType" text NOT NULL,version int DEFAULT 1,"consensusSource" text,"recommendationJson" jsonb NOT NULL,active boolean DEFAULT true,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "ClinicalScoreDefinition" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,name text NOT NULL,description text,"formulaJson" jsonb NOT NULL,"variablesJson" jsonb NOT NULL,category text,active boolean DEFAULT true,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "ClinicalScoreResult" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"patientId" uuid NOT NULL REFERENCES "Patient"(id) ON DELETE CASCADE,"consultationId" uuid,"definitionId" uuid NOT NULL REFERENCES "ClinicalScoreDefinition"(id),"scoreValue" numeric(10,2) NOT NULL,classification text,"variablesInput" jsonb NOT NULL,"calculatedAt" timestamptz DEFAULT now(),"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);

CREATE TABLE IF NOT EXISTS "Appointment" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"clinicId" uuid REFERENCES "Clinic"(id),"patientId" uuid REFERENCES "Patient"(id),"doctorId" uuid NOT NULL,"serviceId" uuid,"startsAt" timestamptz NOT NULL,"endsAt" timestamptz NOT NULL,status appointment_status NOT NULL,notes text,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "TimeSlot" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"clinicId" uuid NOT NULL REFERENCES "Clinic"(id),"doctorId" uuid NOT NULL,"startAt" timestamptz NOT NULL,"endAt" timestamptz NOT NULL,"isBooked" boolean DEFAULT false,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "ServiceDefinition" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"clinicId" uuid REFERENCES "Clinic"(id),name text NOT NULL,active boolean DEFAULT true,type service_type NOT NULL,"contractType" service_contract_type NOT NULL,price numeric(10,2) NOT NULL,"durationMinutes" int NOT NULL,color text,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);
CREATE TABLE IF NOT EXISTS "TemplateElement" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"templateId" uuid NOT NULL,"elementType" text NOT NULL,"positionJson" jsonb NOT NULL,"styleJson" jsonb,"contentJson" jsonb,"createdAt" timestamptz DEFAULT now(),"updatedAt" timestamptz DEFAULT now(),"deletedAt" timestamptz,"createdBy" uuid,"updatedBy" uuid);

CREATE TABLE IF NOT EXISTS "AuditLog" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"actorUserId" uuid,action audit_action NOT NULL,"entityName" text NOT NULL,"entityId" text,"oldData" jsonb,"newData" jsonb,"ipAddress" text,"userAgent" text,"createdAt" timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS "AccessLog" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"actorUserId" uuid,"patientId" uuid,resource text NOT NULL,action text NOT NULL,"ipAddress" text,"userAgent" text,metadata jsonb,"createdAt" timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS "DataExportLog" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"requestedById" uuid NOT NULL,"patientId" uuid,"exportType" text NOT NULL,format text NOT NULL,purpose text NOT NULL,"legalBasis" text NOT NULL,status text NOT NULL,checksum text,"createdAt" timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS "AIInteractionLog" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"patientId" uuid,"consultationId" uuid,"userId" uuid,prompt text NOT NULL,response text NOT NULL,model text NOT NULL,"latencyMs" int,"tokensInput" int,"tokensOutput" int,"piiRedacted" boolean DEFAULT true,"createdAt" timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS "AIExtractionResult" (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" uuid NOT NULL,"patientId" uuid,"consultationId" uuid,"sourceType" text NOT NULL,"sourceRef" text,"extractedJson" jsonb NOT NULL,"confidenceScore" numeric(5,2),"validatedById" uuid,"validatedAt" timestamptz,"createdAt" timestamptz DEFAULT now());


-- Immutable AuditLog enforcement
CREATE OR REPLACE FUNCTION prevent_auditlog_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'AuditLog is immutable (insert-only)';
END;
$$;

DROP TRIGGER IF EXISTS trg_auditlog_no_update ON "AuditLog";
CREATE TRIGGER trg_auditlog_no_update
BEFORE UPDATE ON "AuditLog"
FOR EACH ROW EXECUTE FUNCTION prevent_auditlog_mutation();

DROP TRIGGER IF EXISTS trg_auditlog_no_delete ON "AuditLog";
CREATE TRIGGER trg_auditlog_no_delete
BEFORE DELETE ON "AuditLog"
FOR EACH ROW EXECUTE FUNCTION prevent_auditlog_mutation();
